export const portugueseApiMessages = {
  "api.readiness.note": "O network id 0 da CIP-30 confirma testnet, mas a wallet ainda precisa ser configurada explicitamente para Preprod, não Preview.",
  "api.validation.required": "Campo obrigatório ou inválido: {field}",
  "api.validation.tooLong": "{field} excede {maximumUtf8Bytes} bytes em UTF-8",
  "api.validation.positiveInteger": "{field} precisa ser um número inteiro positivo",
  "api.validation.greaterThanZero": "{field} precisa ser maior que zero",
  "api.validation.maximum": "{field} excede o limite aceito",
  "api.validation.validHexCbor": "{field} precisa ser CBOR hexadecimal válido",
  "api.validation.testnetAddress": "{field} precisa ser um endereço de testnet",
  "api.validation.testnetAddress.guidance": "Selecione Cardano Preprod na wallet e use um endereço addr_test.",
  "api.validation.cardanoAddress": "{field} não é um endereço Cardano válido",
  "api.validation.cardanoAddress.guidance": "Use um endereço addr_test da rede Preprod.",
  "api.validation.eacConnectedWallet": "O saldo EAC do exercício precisa permanecer na wallet conectada",
  "api.validation.eacConnectedWallet.guidance": "Use o endereço da wallet conectada para permitir a aposentadoria posterior.",
  "api.validation.distinctSigners": "Os dois signers precisam usar chaves de pagamento diferentes",
  "api.validation.distinctSigners.guidance": "Conecte ou informe uma segunda wallet com outra chave de pagamento.",
  "api.validation.signedTransaction": "signedTxCbor não representa uma transação Cardano válida",
  "api.validation.signedTransaction.guidance": "Use o signed tx CBOR produzido pela etapa de anexar witnesses.",
  "api.validation.scriptCredential": "scriptAddress precisa usar uma credencial de script",
  "api.validation.scriptUtxoRequired": "scriptUtxo é obrigatório",
  "api.validation.transactionHash": "txHash precisa ter 64 caracteres hexadecimais",
  "api.validation.validMetadataJson": "metadataJson precisa conter um objeto JSON válido",
  "api.validation.issuanceMetadataJson.guidance": "Corrija a sintaxe do JSON e preserve somente os seis campos do schema de emissão EAC.",
  "api.validation.metadataJsonObject": "metadataJson precisa ser um objeto JSON",
  "api.validation.metadataExactKeys": "metadataJson precisa conter exatamente: {keys}",
  "api.validation.issuanceMetadataKeys.guidance": "Não duplique asset name, ação ou quantidade na metadata.",
  "api.validation.issuanceMetadataConstants": "metadataJson precisa usar version 1, unit EAC e decimals 3",
  "api.validation.retirementMetadataKeys.guidance": "Não duplique ação, asset name ou quantidade na metadata.",
  "api.validation.retirementMetadataVersion": "metadataJson precisa usar version 1",
  "api.validation.canonicalHash": "{field} precisa ter exatamente 64 caracteres hexadecimais minúsculos",
  "api.validation.scriptUtxoFormat": "scriptUtxo precisa usar o formato txhash#index",
  "api.invalidJson.message": "O corpo da requisição não é JSON válido",
  "api.invalidJson.guidance": "Corrija o JSON antes de enviar novamente.",
  "api.providerAuthenticationFailed.message": "O Blockfrost recusou a credencial configurada",
  "api.providerAuthenticationFailed.guidance": "Revise BLOCKFROST_PROJECT_ID no backend e reinicie a Workbench.",
  "api.providerRateLimited.message": "O Blockfrost limitou temporariamente as requisições",
  "api.providerRateLimited.guidance": "Aguarde alguns segundos e tente novamente.",
  "api.providerRateLimitedCurrentStep.guidance": "Aguarde alguns segundos e repita somente a etapa atual.",
  "api.blockfrostError.message": "A Preprod não respondeu como esperado",
  "api.blockfrostError.guidance": "Mantenha os artefatos atuais e tente novamente. Se persistir, confirme a configuração do Blockfrost.",
  "api.providerNotReady.message": "O backend ainda não tem uma credencial Blockfrost Preprod",
  "api.providerNotReady.guidance": "Configure BLOCKFROST_PROJECT_ID no backend e reinicie a Workbench.",
  "api.scriptUtxoUnavailable.message": "O UTxO multisig escolhido não está disponível",
  "api.scriptUtxoUnavailable.guidance": "Liste os UTxOs novamente. Se o lock acabou de ser incluído, aguarde a indexação antes de repetir.",
  "api.insufficientFunds.message": "A wallet não possui saldo utilizável suficiente",
  "api.insufficientFunds.guidance": "Confirme Preprod, receba tADA e construa novamente para selecionar UTxOs atuais.",
  "api.invalidAssetMetadata.message": "Os campos do Native Asset não atendem aos limites",
  "api.invalidAssetMetadata.guidance": "Ajuste asset name ou metadata e construa uma nova transação.",
  "api.invalidTransactionCbor.message": "O CBOR da transação não pôde ser decodificado",
  "api.invalidTransactionCbor.guidance": "Use o signed tx CBOR produzido pela etapa de anexar witnesses.",
  "api.transactionExpired.message": "A janela de validade da transação terminou",
  "api.transactionExpired.guidance": "Reinicie o exercício e construa uma nova transação antes de assinar ou submeter.",
  "api.inputAlreadySpent.message": "Um input da transação já foi consumido",
  "api.inputAlreadySpent.guidance": "Consulte novamente a rede e reconstrua a transação com UTxOs atuais.",
  "api.workshopActionFailed.message": "A operação não pôde ser concluída",
  "api.workshopActionFailed.guidance": "Confira os campos e o estado da wallet. Preserve a última etapa válida e tente novamente.",
  "http.backendUnreachable.message": "A Workbench não conseguiu falar com o backend",
  "http.backendUnreachable.guidance": "Confirme que npm run dev continua em execução e tente novamente.",
  "http.invalidBackendResponse.message": "O backend respondeu sem JSON",
  "http.invalidBackendResponse.guidance": "Tente novamente. Se persistir, reinicie o backend.",
  "http.legacyApiError.message": "O backend retornou um erro legado",
  "http.errorWithMessage.message": "O backend respondeu com HTTP e uma mensagem não reconhecida",
  "http.errorWithoutContent.message": "O backend respondeu com HTTP sem conteúdo",
} as const

export const englishApiMessages = {
  "api.readiness.note": "CIP-30 network ID 0 confirms testnet, but the wallet must still be set explicitly to Preprod, not Preview.",
  "api.validation.required": "Required or invalid field: {field}",
  "api.validation.tooLong": "{field} exceeds {maximumUtf8Bytes} UTF-8 bytes",
  "api.validation.positiveInteger": "{field} must be a positive integer",
  "api.validation.greaterThanZero": "{field} must be greater than zero",
  "api.validation.maximum": "{field} exceeds the accepted limit",
  "api.validation.validHexCbor": "{field} must be valid hexadecimal CBOR",
  "api.validation.testnetAddress": "{field} must be a testnet address",
  "api.validation.testnetAddress.guidance": "Select Cardano Preprod in the wallet and use an addr_test address.",
  "api.validation.cardanoAddress": "{field} is not a valid Cardano address",
  "api.validation.cardanoAddress.guidance": "Use an addr_test address from the Preprod network.",
  "api.validation.eacConnectedWallet": "The exercise EAC balance must remain in the connected wallet",
  "api.validation.eacConnectedWallet.guidance": "Use the connected wallet address to allow later retirement.",
  "api.validation.distinctSigners": "The two signers must use different payment keys",
  "api.validation.distinctSigners.guidance": "Connect or enter a second wallet with a different payment key.",
  "api.validation.signedTransaction": "signedTxCbor does not represent a valid Cardano transaction",
  "api.validation.signedTransaction.guidance": "Use the signed transaction CBOR produced by the witness attachment step.",
  "api.validation.scriptCredential": "scriptAddress must use a script credential",
  "api.validation.scriptUtxoRequired": "scriptUtxo is required",
  "api.validation.transactionHash": "txHash must contain 64 hexadecimal characters",
  "api.validation.validMetadataJson": "metadataJson must contain a valid JSON object",
  "api.validation.issuanceMetadataJson.guidance": "Correct the JSON syntax and keep only the six fields in the EAC issuance schema.",
  "api.validation.metadataJsonObject": "metadataJson must be a JSON object",
  "api.validation.metadataExactKeys": "metadataJson must contain exactly: {keys}",
  "api.validation.issuanceMetadataKeys.guidance": "Do not duplicate asset name, action, or quantity in the metadata.",
  "api.validation.issuanceMetadataConstants": "metadataJson must use version 1, unit EAC, and decimals 3",
  "api.validation.retirementMetadataKeys.guidance": "Do not duplicate action, asset name, or quantity in the metadata.",
  "api.validation.retirementMetadataVersion": "metadataJson must use version 1",
  "api.validation.canonicalHash": "{field} must contain exactly 64 lowercase hexadecimal characters",
  "api.validation.scriptUtxoFormat": "scriptUtxo must use the txhash#index format",
  "api.invalidJson.message": "The request body is not valid JSON",
  "api.invalidJson.guidance": "Correct the JSON before sending it again.",
  "api.providerAuthenticationFailed.message": "Blockfrost rejected the configured credential",
  "api.providerAuthenticationFailed.guidance": "Review BLOCKFROST_PROJECT_ID in the backend and restart the Workbench.",
  "api.providerRateLimited.message": "Blockfrost has temporarily rate-limited requests",
  "api.providerRateLimited.guidance": "Wait a few seconds and try again.",
  "api.providerRateLimitedCurrentStep.guidance": "Wait a few seconds and repeat only the current step.",
  "api.blockfrostError.message": "Preprod did not respond as expected",
  "api.blockfrostError.guidance": "Keep the current artifacts and try again. If it persists, confirm the Blockfrost configuration.",
  "api.providerNotReady.message": "The backend does not have a Blockfrost Preprod credential yet",
  "api.providerNotReady.guidance": "Configure BLOCKFROST_PROJECT_ID in the backend and restart the Workbench.",
  "api.scriptUtxoUnavailable.message": "The selected multisig UTxO is unavailable",
  "api.scriptUtxoUnavailable.guidance": "List the UTxOs again. If the lock was just included, wait for indexing before repeating.",
  "api.insufficientFunds.message": "The wallet does not have enough usable funds",
  "api.insufficientFunds.guidance": "Confirm Preprod, receive tADA, and build again to select current UTxOs.",
  "api.invalidAssetMetadata.message": "The Native Asset fields do not meet the limits",
  "api.invalidAssetMetadata.guidance": "Adjust the asset name or metadata and build a new transaction.",
  "api.invalidTransactionCbor.message": "The transaction CBOR could not be decoded",
  "api.invalidTransactionCbor.guidance": "Use the signed transaction CBOR produced by the witness attachment step.",
  "api.transactionExpired.message": "The transaction validity window ended",
  "api.transactionExpired.guidance": "Restart the exercise and build a new transaction before signing or submitting.",
  "api.inputAlreadySpent.message": "A transaction input has already been consumed",
  "api.inputAlreadySpent.guidance": "Query the network again and rebuild the transaction with current UTxOs.",
  "api.workshopActionFailed.message": "The operation could not be completed",
  "api.workshopActionFailed.guidance": "Check the fields and wallet state. Preserve the last valid step and try again.",
  "http.backendUnreachable.message": "The Workbench could not reach the backend",
  "http.backendUnreachable.guidance": "Confirm that npm run dev is still running and try again.",
  "http.invalidBackendResponse.message": "The backend responded without JSON",
  "http.invalidBackendResponse.guidance": "Try again. If it persists, restart the backend.",
  "http.legacyApiError.message": "The backend returned a legacy error",
  "http.errorWithMessage.message": "The backend responded with HTTP and an unrecognized message",
  "http.errorWithoutContent.message": "The backend responded with HTTP and no content",
} as const satisfies Record<keyof typeof portugueseApiMessages, string>
