export const portugueseFlowMessages = {
  "locale.selector.label": "Idioma",
  "locale.selector.portuguese": "Português (Brasil)",
  "locale.selector.english": "English",
  "flow.notice.built": "Transação construída. Confira os detalhes antes de pedir a assinatura.",
  "flow.notice.importedUnsigned": "CBOR importado. Ele ainda precisa ser assinado pela wallet correta.",
  "flow.notice.witnessesComplete": "Todas as assinaturas necessárias estão disponíveis.",
  "flow.notice.witnessesPartial": "{supplied} de {required} assinaturas disponíveis.",
  "flow.notice.merged": "Witnesses anexados. Revise o efeito antes de submeter.",
  "flow.notice.submissionUnknown": "Hash calculado localmente. A resposta da submissão ainda é desconhecida.",
  "flow.notice.submitted": "Transação aceita pelo Blockfrost. A inclusão em bloco ainda precisa ser confirmada.",
  "flow.notice.included": "Transação incluída no bloco {blockHeight}.",
  "flow.notice.inputsInvalidated": "Estas entradas não correspondem mais à transação anterior. CBOR sem assinatura, witnesses, CBOR assinado, revisão e hash exibido foram limpos. Construa novamente. Qualquer transação já submetida à Preprod permanece inalterada.",
  "flow.notice.buildingNew": "Construindo uma nova transação.",
  "flow.notice.notIndexed": "O Blockfrost ainda não indexa este hash. Isso não confirma nem rejeita a submissão. Aguarde e verifique novamente.",
  "flow.error.submissionUnknown.message": "O resultado da submissão é desconhecido",
  "flow.error.submissionUnknown.guidance": "Use o hash calculado e verifique a inclusão antes de tentar submeter o mesmo signed CBOR novamente.",
  "flow.error.eacExpired.message": "A transação EAC expirou",
  "flow.error.eacExpired.guidance": "Reinicie a emissão e construa uma nova transação. A policy permanece a mesma; somente a validade da transação será renovada.",
  "flow.error.mintExpired.message": "A validade da policy do mint expirou",
  "flow.error.mintExpired.guidance": "Reinicie o exercício e construa um novo mint para obter outra janela de validade.",
  "flow.error.transactionExpired.message": "A transação expirou",
  "flow.error.transactionExpired.guidance": "Reconstrua a transação para obter uma nova janela de validade antes de assinar e submeter.",
  "flow.error.backend.message": "O backend rejeitou esta etapa",
  "flow.error.sign.message": "A wallet não produziu a assinatura",
  "flow.error.generic.message": "A etapa não pôde ser concluída",
  "flow.error.invalidImportedMultisig.message": "O unsigned CBOR importado não passou na validação multisig",
  "flow.error.invalidImportedMultisig.guidance": "Confirme que recebeu o CBOR de unlock correto e cole novamente. Nenhuma assinatura foi produzida.",
  "flow.error.noTechnicalDetail": "Sem detalhe técnico adicional.",
  "flow.guidance.build": "Confira os campos, a rede Preprod e o saldo de tADA. Depois, tente construir novamente.",
  "flow.guidance.sign": "Confira a extensão, conecte a wallet correta e aprove a assinatura. Depois, tente novamente.",
  "flow.guidance.merge": "Confira se os witnesses pertencem ao mesmo unsigned CBOR e tente anexá-los novamente.",
  "flow.guidance.submit": "Preserve o signed CBOR e o hash, se houver. Tente novamente ou consulte o Cardanoscan antes de reconstruir.",
  "flow.guidance.check": "Aguarde alguns segundos e verifique novamente. O hash submetido foi preservado.",
  "flow.status.failed": "A etapa falhou. {guidance}",
  "flow.status.draft": "Próximo passo: preencha os campos e construa a transação.",
  "flow.status.waitBackend": "Aguarde: o backend e o Blockfrost Preprod precisam estar prontos antes de construir.",
  "flow.status.connectWallet": "Próximo passo: conecte uma wallet CIP-30 na seção de prontidão.",
  "flow.status.fundWallet": "A wallet conectada ainda não tem um UTxO Preprod indexado. Confirme a rede e o saldo.",
  "flow.status.built": "Próximo passo: confira o unsigned CBOR e peça a assinatura da wallet.",
  "flow.status.partiallySigned": "Próximo passo: obtenha o witness que ainda falta.",
  "flow.status.signed": "Próximo passo: anexe os witnesses à transação.",
  "flow.status.merged": "Próximo passo: revise o efeito, confirme a ciência e submeta na Preprod.",
  "flow.status.submissionUnknown": "O hash foi calculado, mas o resultado da submissão é desconhecido. Verifique a inclusão antes de reconstruir.",
  "flow.status.submitted": "Próximo passo: aguarde a indexação ou verifique novamente.",
  "flow.status.included": "Concluído: a transação foi incluída em um bloco da Preprod.",
  "flow.busy.build": "Construindo a transação com o estado atual da Preprod...",
  "flow.busy.sign": "Aguardando a decisão na extensão da wallet...",
  "flow.busy.merge": "Validando e anexando os witnesses...",
  "flow.busy.submit": "Submetendo a transação assinada à Preprod...",
  "flow.busy.check": "Verificando a inclusão da transação...",
  "flow.action.retry": "Tentar novamente",
  "flow.action.checkInclusion": "Verificar inclusão",
  "flow.reset.confirm": "Reiniciar limpa somente o estado local. A transação já submetida continua na Preprod. Continuar?",
  "flow.concurrent.message": "Outra etapa da Workbench ainda está em andamento",
  "flow.log.reset": "Fluxo {flow}: estado local reiniciado.",
  "flow.log.invalidated": "Fluxo {flow}: artefatos anteriores invalidados.",
  "flow.log.imported": "Fluxo {flow}: unsigned CBOR importado, inspecionado e pronto para revisão.",
  "flow.log.importRejected": "Fluxo {flow}: CBOR importado rejeitado.",
  "flow.log.witnessUpdated": "Fluxo {flow}: witness recebido atualizado.",
  "flow.log.built": "Fluxo {flow}: unsigned transaction construída.",
  "flow.log.signed": "Fluxo {flow}: witness criado pela wallet conectada.",
  "flow.log.merged": "Fluxo {flow}: witnesses validados e anexados.",
  "flow.log.submitted": "Fluxo {flow}: submetida com hash {txHash}.",
  "flow.log.included": "Fluxo {flow}: incluída no bloco {blockHeight}.",
  "flow.log.failed": "Fluxo {flow}: a etapa falhou.",
  "flow.title.payment": "Pagamento simples",
  "flow.title.metadata": "Pagamento com metadata",
  "flow.title.multisigLock": "Multisig lock",
  "flow.title.multisigUnlock": "Multisig unlock",
  "flow.title.eacMint": "Emissão EAC com metadata raw",
  "flow.title.eacRetire": "Aposentadoria EAC com burn",
  "flow.title.mint": "Native Asset CIP-25",
  "flow.completion.exerciseLabel": "Exercício concluído",
  "flow.completion.stepLabel": "Etapa concluída",
  "flow.completion.payment": "A transação foi incluída em um bloco da Preprod. Confira destino, valor e taxa no Cardanoscan.",
  "flow.completion.metadata": "A transação foi incluída. Abra o Cardanoscan e localize o label 674 e a mensagem publicada.",
  "flow.completion.multisigLock": "O lock foi incluído. Agora use “Listar UTxOs do script”. Se o UTxO ainda não aparecer, aguarde a indexação e tente novamente.",
  "flow.completion.multisigUnlock": "O UTxO escolhido foi consumido e o valor saiu para o destino, mas o troco continua bloqueado no script. Para recuperar mais tADA, reinicie somente o unlock, liste o novo UTxO e repita com as duas wallets.",
  "flow.completion.eacMint": "A emissão didática foi incluída. Confira 1.000.000 unidades-base no campo mint e aguarde a indexação antes de construir a aposentadoria.",
  "flow.completion.eacRetire": "A aposentadoria foi incluída. Confira o burn de -125.000 unidades-base e o saldo de 875.000 unidades-base no output da wallet.",
  "flow.completion.mint": "A transação de mint foi incluída. Confira policy id, asset name, quantidade e metadata 721 no Cardanoscan.",
  "review.unavailable.transaction": "Construa e assine a transação para ver o resumo.",
  "review.unavailable.mint": "Construa e assine o mint para ver o resumo.",
  "review.unavailable.eacMint": "Construa e assine a emissão EAC para ver o resumo.",
  "review.unavailable.eacRetire": "Construa e assine a aposentadoria EAC para ver o resumo.",
  "review.unavailable.multisigLock": "Construa e assine o lock para ver o resumo.",
  "review.unavailable.multisigUnlock": "Construa, colete e anexe os witnesses para ver o resumo.",
  "review.value.unavailable": "não disponível",
  "review.value.notFound": "não localizado",
  "review.value.quantityUnavailable": "quantidade indisponível",
  "review.payment": "{network}. O CBOR contém output de {lovelace} lovelace para {recipient}. Taxa calculada no corpo: {fee} lovelace. Confira também inputs e troco na confirmação da wallet.",
  "review.metadata": "{network}. O CBOR contém output de {lovelace} lovelace para {recipient} e mensagem pública no label 674: “{message}”. Taxa calculada no corpo: {fee} lovelace.",
  "review.mint": "{network}. O CBOR contém mint de {quantity} {unitLabel} de {tokenName} e output de {outputQuantity} para {recipient}. Policy {policyId}. Validade até {expiry}. Taxa calculada no corpo: {fee} lovelace.",
  "review.unit.one": "unidade",
  "review.unit.other": "unidades",
  "review.eacMint": "{network}. O CBOR contém emissão de {quantity} unidades-base ({displayQuantity}) de {tokenName} e output de {outputQuantity} unidades-base para o endereço contábil {recipient}. Metadata raw no label 65536: version {version}, unit {unit}, decimals {decimals} e três hashes sintéticos. A policy verifica somente a chave autorizada; não valida a metadata nem limita a oferta. Validade desta transação até {expiry}. Taxa calculada no corpo: {fee} lovelace.",
  "review.eacRetire": "{network}. O CBOR contém burn de {quantity} unidades-base ({displayQuantity}) de {tokenName} e devolve saldo de {remaining} unidades-base ({displayRemaining}) à wallet contábil {recipient}. Metadata no label 65536: version {version}, declaration_hash e delivery_reference_hash. A policy verifica somente a chave autorizada; não comprova alegações externas. Validade desta transação até {expiry}. Taxa calculada no corpo: {fee} lovelace.",
  "review.multisigLock": "{network}. O CBOR contém lock de {lovelace} lovelace no script {scriptAddress}. As duas chaves listadas em requiredSigners serão necessárias para desbloquear. Taxa calculada no corpo: {fee} lovelace.",
  "review.multisigUnlock": "{network}. O CBOR referencia o input {input}, que será confirmado no script antes da assinatura; envia {destinationLovelace} lovelace para {destination} e devolve {changeLovelace} lovelace ao script. Required signers: {signers}. Taxa calculada no corpo: {fee} lovelace.",
  "readiness.wallet.none": "Nenhuma wallet CIP-30 detectada",
  "readiness.status.checking": "Verificando",
  "readiness.status.pending": "Pendente",
  "readiness.status.ready": "Pronto",
  "readiness.status.warning": "Atenção",
  "readiness.status.error": "Erro",
  "readiness.item.backend": "Backend local",
  "readiness.item.provider": "Blockfrost Preprod",
  "readiness.item.extension": "Wallet CIP-30",
  "readiness.item.network": "Wallet em testnet",
  "readiness.item.funding": "Saldo de tADA",
  "readiness.item.label": "{title}: {status}",
  "readiness.message.checking": "Verificando backend e Blockfrost Preprod...",
  "readiness.message.error": "Não foi possível verificar o ambiente. Confirme que npm run dev está em execução.",
  "readiness.message.providerMissing": "Configure BLOCKFROST_PROJECT_ID no backend e reinicie a Workbench.",
  "readiness.message.providerUnavailable": "O Blockfrost Preprod está indisponível. Seus campos e artefatos continuam nesta aba; aguarde e tente novamente.",
  "readiness.message.connectWallet": "Backend pronto. Conecte uma wallet configurada em Preprod.",
  "readiness.message.walletUnfunded": "Wallet conectada, mas sem UTxO visível na Preprod. Confirme a rede e receba tADA.",
  "readiness.message.ready.one": "Ambiente pronto. 1 UTxO encontrado para esta wallet.",
  "readiness.message.ready.other": "Ambiente pronto. {count} UTxOs encontrados para esta wallet.",
  "wallet.status.waitCurrent": "Aguarde a etapa em andamento antes de trocar a wallet.",
  "wallet.status.authorizing": "Aguardando autorização da extensão...",
  "wallet.status.connectFailed": "Não foi possível conectar a wallet. Confira a extensão e tente novamente.",
  "wallet.error.notFound": "A wallet selecionada não foi encontrada no navegador",
  "wallet.error.networkConfiguration": "A configuração de rede do backend não está disponível ou não corresponde à Preprod.",
  "wallet.error.mainnet": "A wallet está na mainnet. Selecione Cardano Preprod na extensão e conecte novamente.",
  "wallet.error.required": "Conecte uma wallet CIP-30 em Preprod primeiro",
  "wallet.log.connected": "Wallet conectada: {providerName} em testnet, {address}",
  "wallet.log.connectFailed": "Falha ao conectar wallet.",
  "readiness.log.failed": "Falha ao verificar o ambiente.",
  "clipboard.copy": "Copiar",
  "clipboard.copied": "Copiado",
  "clipboard.failed": "Falhou",
  "clipboard.status.success": "{label}: concluído.",
  "clipboard.status.failed": "{label}: falhou. {message}",
  "clipboard.error.empty": "Este artefato ainda está vazio",
  "clipboard.error.generic": "Não foi possível copiar este artefato",
  "clipboard.log.copied": "Artefato copiado: {target}",
  "clipboard.log.failed": "Falha ao copiar o artefato {target}.",
  "artifact.copyLabel": "Copiar {title}",
  "artifact.description.generic": "Artefato técnico desta etapa.",
  "artifact.title.details": "Detalhes da construção",
  "artifact.title.unsigned": "Unsigned tx CBOR",
  "artifact.title.witness": "Witness set CBOR",
  "artifact.title.signed": "Signed tx CBOR",
  "artifact.title.hash": "Tx hash",
  "artifact.title.multisigDetails": "Native script e endereço",
  "artifact.title.multisigUtxos": "UTxOs disponíveis",
  "artifact.title.lockDetails": "Detalhes do lock",
  "artifact.title.unlockDetails": "Detalhes do unlock",
  "artifact.title.receivedWitness": "Witness recebido",
  "artifact.title.currentWitness": "Witness da wallet atual",
  "artifact.title.eacDetails": "Policy, asset e metadata raw",
  "artifact.title.retireDetails": "Policy, burn e metadata",
  "artifact.title.mintDetails": "Policy, asset e metadata",
  "artifact.description.details": "Compare as entradas informadas com os efeitos e o corpo calculado.",
  "artifact.description.unsigned": "Transação antes da autorização da wallet.",
  "artifact.description.witness": "Assinatura específica para este corpo de transação.",
  "artifact.description.signed": "Transação pronta para revisão e submissão.",
  "artifact.description.hash": "Identificador usado para acompanhar a inclusão na rede.",
  "artifact.description.multisigDetails": "Inclui script 2-de-2, hashes das duas chaves e script address.",
  "artifact.description.multisigUtxos": "Estado atual do script segundo o Blockfrost Preprod.",
  "artifact.description.lockDetails": "Mostra script address, signers, valor e corpo calculado.",
  "artifact.description.unlockDetails": "Mostra UTxO consumido, destino, signers e troco do script.",
  "artifact.description.receivedWitness": "Signer A cola aqui o witness devolvido pelo signer B.",
  "artifact.description.currentWitness": "Signer B copia este witness e o envia ao signer A.",
  "artifact.description.eacDetails": "Inclui policy id, script estável, label 65536, payload e resumo da transação.",
  "artifact.description.retireDetails": "Inclui policy id, burn, saldo restante e referências de aposentadoria.",
  "artifact.description.mintDetails": "Inclui policy id, script, validade, metadata 721 e resumo da transação.",
  "multisig.status.initial": "Conecte o signer A e informe o endereço do signer B.",
  "multisig.status.invalidated": "O setup multisig foi invalidado porque os signers mudaram.",
  "multisig.status.signerChanged": "O signer A mudou. Gere e revise novamente o script 2-de-2.",
  "multisig.status.connectAgain": "Conecte novamente o signer A e gere o script 2-de-2.",
  "multisig.status.generating": "Gerando o script 2-de-2...",
  "multisig.status.generated": "Script criado. Abra os detalhes e confira endereço e hashes antes de autorizar o lock.",
  "multisig.status.listing": "Consultando UTxOs do script na Preprod...",
  "multisig.status.none": "Nenhum UTxO indexado ainda. Se o lock foi incluído agora, aguarde alguns segundos e tente novamente.",
  "multisig.status.one": "UTxO único selecionado: {outRef}",
  "multisig.status.many": "Há vários UTxOs. Escolha explicitamente qual deles o unlock deve consumir.",
  "multisig.status.waitCurrent": "Aguarde a etapa em andamento antes de iniciar o setup multisig.",
  "multisig.status.recover": "Corrija o problema indicado e repita esta etapa.",
  "multisig.error.generic": "Não foi possível concluir a etapa multisig",
  "multisig.guidance.generic": "Confira as duas wallets, a rede Preprod e os endereços. Depois, tente novamente.",
  "multisig.guidance.retry": "Tente novamente.",
  "multisig.choice.label": "{outRef} | {lovelace} lovelace",
  "multisig.log.generated": "Multisig: script 2-de-2 gerado com duas chaves distintas.",
  "multisig.log.failed": "A etapa de setup multisig falhou.",
  "multisig.error.setupRequired": "Gere e confirme novamente o setup multisig antes de continuar",
  "multisig.error.walletMismatch": "A wallet conectada não corresponde à chave que construiu esta transação",
  "multisig.error.contextMissing": "O CBOR não informa script address e UTxO para verificação",
  "multisig.error.notRequiredSigner": "A wallet conectada não pertence aos required signers deste unlock",
  "session.description": "Salva nesta aba em {savedAt}. A wallet e o setup multisig deverão ser validados novamente.",
  "session.log.busy": "Aguarde a etapa em andamento antes de restaurar a sessão.",
  "session.log.restored": "Sessão restaurada. Reconecte a wallet antes de assinar ou construir.",
  "session.log.discarded": "Sessão salva descartada.",
  "technicalLog.newError.one": "Novo erro no log técnico.",
  "technicalLog.newError.other": "{count} erros não lidos no log técnico.",
  "technicalLog.open": "Abrir log técnico",
  "technicalLog.openUnread.one": "Abrir log técnico, 1 erro não lido",
  "technicalLog.openUnread.other": "Abrir log técnico, {count} erros não lidos",
} as const

export const englishFlowMessages = {
  "locale.selector.label": "Language",
  "locale.selector.portuguese": "Português (Brasil)",
  "locale.selector.english": "English",
  "flow.notice.built": "Transaction built. Review the details before requesting a signature.",
  "flow.notice.importedUnsigned": "CBOR imported. It still needs to be signed by the correct wallet.",
  "flow.notice.witnessesComplete": "All required signatures are available.",
  "flow.notice.witnessesPartial": "{supplied} of {required} signatures available.",
  "flow.notice.merged": "Witnesses attached. Review the effect before submitting.",
  "flow.notice.submissionUnknown": "Hash calculated locally. The submission response is still unknown.",
  "flow.notice.submitted": "Transaction accepted by Blockfrost. Block inclusion still needs confirmation.",
  "flow.notice.included": "Transaction included in block {blockHeight}.",
  "flow.notice.inputsInvalidated": "These inputs no longer match the previous transaction. The unsigned CBOR, witnesses, signed CBOR, review, and displayed hash were cleared. Build again. Any transaction already submitted to Preprod is unchanged.",
  "flow.notice.buildingNew": "Building a new transaction.",
  "flow.notice.notIndexed": "Blockfrost has not indexed this hash yet. This neither confirms nor rejects the submission. Wait and check again.",
  "flow.error.submissionUnknown.message": "The submission result is unknown",
  "flow.error.submissionUnknown.guidance": "Use the calculated hash and check inclusion before trying to submit the same signed CBOR again.",
  "flow.error.eacExpired.message": "The EAC transaction expired",
  "flow.error.eacExpired.guidance": "Restart issuance and build a new transaction. The policy remains the same; only the transaction validity will be renewed.",
  "flow.error.mintExpired.message": "The mint policy validity expired",
  "flow.error.mintExpired.guidance": "Restart the exercise and build a new mint to obtain another validity window.",
  "flow.error.transactionExpired.message": "The transaction expired",
  "flow.error.transactionExpired.guidance": "Rebuild the transaction to obtain a new validity window before signing and submitting.",
  "flow.error.backend.message": "The backend rejected this step",
  "flow.error.sign.message": "The wallet did not produce a signature",
  "flow.error.generic.message": "The step could not be completed",
  "flow.error.invalidImportedMultisig.message": "The imported unsigned CBOR failed multisig validation",
  "flow.error.invalidImportedMultisig.guidance": "Confirm that you received the correct unlock CBOR and paste it again. No signature was produced.",
  "flow.error.noTechnicalDetail": "No additional technical detail.",
  "flow.guidance.build": "Check the fields, the Preprod network, and the tADA balance. Then try building again.",
  "flow.guidance.sign": "Check the extension, connect the correct wallet, and approve the signature. Then try again.",
  "flow.guidance.merge": "Check that the witnesses belong to the same unsigned CBOR and try attaching them again.",
  "flow.guidance.submit": "Preserve the signed CBOR and the hash, if available. Try again or check Cardanoscan before rebuilding.",
  "flow.guidance.check": "Wait a few seconds and check again. The submitted hash was preserved.",
  "flow.status.failed": "The step failed. {guidance}",
  "flow.status.draft": "Next step: fill in the fields and build the transaction.",
  "flow.status.waitBackend": "Wait until the backend and Blockfrost Preprod are ready before building.",
  "flow.status.connectWallet": "Next step: connect a CIP-30 wallet in the readiness section.",
  "flow.status.fundWallet": "The connected wallet does not yet have an indexed Preprod UTxO. Confirm the network and balance.",
  "flow.status.built": "Next step: review the unsigned CBOR and request the wallet signature.",
  "flow.status.partiallySigned": "Next step: obtain the remaining witness.",
  "flow.status.signed": "Next step: attach the witnesses to the transaction.",
  "flow.status.merged": "Next step: review the effect, acknowledge it, and submit on Preprod.",
  "flow.status.submissionUnknown": "The hash was calculated, but the submission result is unknown. Check inclusion before rebuilding.",
  "flow.status.submitted": "Next step: wait for indexing or check again.",
  "flow.status.included": "Complete: the transaction was included in a Preprod block.",
  "flow.busy.build": "Building the transaction with the current Preprod state...",
  "flow.busy.sign": "Waiting for a decision in the wallet extension...",
  "flow.busy.merge": "Validating and attaching witnesses...",
  "flow.busy.submit": "Submitting the signed transaction to Preprod...",
  "flow.busy.check": "Checking transaction inclusion...",
  "flow.action.retry": "Try again",
  "flow.action.checkInclusion": "Check inclusion",
  "flow.reset.confirm": "Resetting clears only local state. A transaction already submitted remains on Preprod. Continue?",
  "flow.concurrent.message": "Another Workbench step is still in progress",
  "flow.log.reset": "Flow {flow}: local state reset.",
  "flow.log.invalidated": "Flow {flow}: previous artifacts invalidated.",
  "flow.log.imported": "Flow {flow}: unsigned CBOR imported, inspected, and ready for review.",
  "flow.log.importRejected": "Flow {flow}: imported CBOR rejected.",
  "flow.log.witnessUpdated": "Flow {flow}: received witness updated.",
  "flow.log.built": "Flow {flow}: unsigned transaction built.",
  "flow.log.signed": "Flow {flow}: witness created by the connected wallet.",
  "flow.log.merged": "Flow {flow}: witnesses validated and attached.",
  "flow.log.submitted": "Flow {flow}: submitted with hash {txHash}.",
  "flow.log.included": "Flow {flow}: included in block {blockHeight}.",
  "flow.log.failed": "Flow {flow}: the step failed.",
  "flow.title.payment": "Simple payment",
  "flow.title.metadata": "Payment with metadata",
  "flow.title.multisigLock": "Multisig lock",
  "flow.title.multisigUnlock": "Multisig unlock",
  "flow.title.eacMint": "EAC issuance with raw metadata",
  "flow.title.eacRetire": "EAC retirement with burn",
  "flow.title.mint": "CIP-25 Native Asset",
  "flow.completion.exerciseLabel": "Exercise complete",
  "flow.completion.stepLabel": "Step complete",
  "flow.completion.payment": "The transaction was included in a Preprod block. Verify the destination, amount, and fee on Cardanoscan.",
  "flow.completion.metadata": "The transaction was included. Open Cardanoscan and locate label 674 and the published message.",
  "flow.completion.multisigLock": "The lock was included. Now use “List script UTxOs”. If the UTxO does not appear yet, wait for indexing and try again.",
  "flow.completion.multisigUnlock": "The selected UTxO was consumed and the amount went to the destination, but the change remains locked in the script. To recover more tADA, reset only the unlock, list the new UTxO, and repeat with both wallets.",
  "flow.completion.eacMint": "The training issuance was included. Check 1,000,000 base units in the mint field and wait for indexing before building the retirement.",
  "flow.completion.eacRetire": "The retirement was included. Check the burn of -125,000 base units and the remaining 875,000 base units in the wallet output.",
  "flow.completion.mint": "The mint transaction was included. Check the policy ID, asset name, quantity, and metadata under label 721 on Cardanoscan.",
  "review.unavailable.transaction": "Build and sign the transaction to see the summary.",
  "review.unavailable.mint": "Build and sign the mint to see the summary.",
  "review.unavailable.eacMint": "Build and sign the EAC issuance to see the summary.",
  "review.unavailable.eacRetire": "Build and sign the EAC retirement to see the summary.",
  "review.unavailable.multisigLock": "Build and sign the lock to see the summary.",
  "review.unavailable.multisigUnlock": "Build, collect, and attach the witnesses to see the summary.",
  "review.value.unavailable": "unavailable",
  "review.value.notFound": "not found",
  "review.value.quantityUnavailable": "quantity unavailable",
  "review.payment": "{network}. The CBOR contains an output of {lovelace} lovelace to {recipient}. Fee calculated in the body: {fee} lovelace. Also check inputs and change in the wallet confirmation.",
  "review.metadata": "{network}. The CBOR contains an output of {lovelace} lovelace to {recipient} and a public message under label 674: “{message}”. Fee calculated in the body: {fee} lovelace.",
  "review.mint": "{network}. The CBOR contains a mint of {quantity} {unitLabel} of {tokenName} and an output of {outputQuantity} to {recipient}. Policy {policyId}. Valid until {expiry}. Fee calculated in the body: {fee} lovelace.",
  "review.unit.one": "unit",
  "review.unit.other": "units",
  "review.eacMint": "{network}. The CBOR contains an issuance of {quantity} base units ({displayQuantity}) of {tokenName} and an output of {outputQuantity} base units to accounting address {recipient}. Raw metadata under label 65536: version {version}, unit {unit}, decimals {decimals}, and three synthetic hashes. The policy checks only the authorized key; it does not validate metadata or limit supply. This transaction is valid until {expiry}. Fee calculated in the body: {fee} lovelace.",
  "review.eacRetire": "{network}. The CBOR contains a burn of {quantity} base units ({displayQuantity}) of {tokenName} and returns a balance of {remaining} base units ({displayRemaining}) to accounting wallet {recipient}. Metadata under label 65536: version {version}, declaration_hash, and delivery_reference_hash. The policy checks only the authorized key; it does not verify external claims. This transaction is valid until {expiry}. Fee calculated in the body: {fee} lovelace.",
  "review.multisigLock": "{network}. The CBOR contains a lock of {lovelace} lovelace at script {scriptAddress}. Both keys listed in requiredSigners will be needed to unlock it. Fee calculated in the body: {fee} lovelace.",
  "review.multisigUnlock": "{network}. The CBOR references input {input}, which will be confirmed at the script before signing; sends {destinationLovelace} lovelace to {destination} and returns {changeLovelace} lovelace to the script. Required signers: {signers}. Fee calculated in the body: {fee} lovelace.",
  "readiness.wallet.none": "No CIP-30 wallet detected",
  "readiness.status.checking": "Checking",
  "readiness.status.pending": "Pending",
  "readiness.status.ready": "Ready",
  "readiness.status.warning": "Attention",
  "readiness.status.error": "Error",
  "readiness.item.backend": "Local backend",
  "readiness.item.provider": "Blockfrost Preprod",
  "readiness.item.extension": "CIP-30 wallet",
  "readiness.item.network": "Wallet on testnet",
  "readiness.item.funding": "tADA balance",
  "readiness.item.label": "{title}: {status}",
  "readiness.message.checking": "Checking backend and Blockfrost Preprod...",
  "readiness.message.error": "Could not check the environment. Confirm that npm run dev is running.",
  "readiness.message.providerMissing": "Configure BLOCKFROST_PROJECT_ID in the backend and restart the Workbench.",
  "readiness.message.providerUnavailable": "Blockfrost Preprod is unavailable. Your fields and artifacts remain in this tab; wait and try again.",
  "readiness.message.connectWallet": "Backend ready. Connect a wallet configured for Preprod.",
  "readiness.message.walletUnfunded": "Wallet connected, but no UTxO is visible on Preprod. Confirm the network and receive tADA.",
  "readiness.message.ready.one": "Environment ready. 1 UTxO found for this wallet.",
  "readiness.message.ready.other": "Environment ready. {count} UTxOs found for this wallet.",
  "wallet.status.waitCurrent": "Wait for the current step to finish before changing wallets.",
  "wallet.status.authorizing": "Waiting for extension authorization...",
  "wallet.status.connectFailed": "Could not connect the wallet. Check the extension and try again.",
  "wallet.error.notFound": "The selected wallet was not found in the browser",
  "wallet.error.networkConfiguration": "The backend network configuration is unavailable or does not match Preprod.",
  "wallet.error.mainnet": "The wallet is on mainnet. Select Cardano Preprod in the extension and connect again.",
  "wallet.error.required": "Connect a CIP-30 wallet on Preprod first",
  "wallet.log.connected": "Wallet connected: {providerName} on testnet, {address}",
  "wallet.log.connectFailed": "Wallet connection failed.",
  "readiness.log.failed": "Environment check failed.",
  "clipboard.copy": "Copy",
  "clipboard.copied": "Copied",
  "clipboard.failed": "Failed",
  "clipboard.status.success": "{label}: complete.",
  "clipboard.status.failed": "{label}: failed. {message}",
  "clipboard.error.empty": "This artifact is still empty",
  "clipboard.error.generic": "This artifact could not be copied",
  "clipboard.log.copied": "Artifact copied: {target}",
  "clipboard.log.failed": "Failed to copy artifact {target}.",
  "artifact.copyLabel": "Copy {title}",
  "artifact.description.generic": "Technical artifact for this step.",
  "artifact.title.details": "Build details",
  "artifact.title.unsigned": "Unsigned tx CBOR",
  "artifact.title.witness": "Witness set CBOR",
  "artifact.title.signed": "Signed tx CBOR",
  "artifact.title.hash": "Tx hash",
  "artifact.title.multisigDetails": "Native script and address",
  "artifact.title.multisigUtxos": "Available UTxOs",
  "artifact.title.lockDetails": "Lock details",
  "artifact.title.unlockDetails": "Unlock details",
  "artifact.title.receivedWitness": "Received witness",
  "artifact.title.currentWitness": "Current wallet witness",
  "artifact.title.eacDetails": "Policy, asset, and raw metadata",
  "artifact.title.retireDetails": "Policy, burn, and metadata",
  "artifact.title.mintDetails": "Policy, asset, and metadata",
  "artifact.description.details": "Compare the provided inputs with the calculated effects and body.",
  "artifact.description.unsigned": "Transaction before wallet authorization.",
  "artifact.description.witness": "Signature specific to this transaction body.",
  "artifact.description.signed": "Transaction ready for review and submission.",
  "artifact.description.hash": "Identifier used to track network inclusion.",
  "artifact.description.multisigDetails": "Includes the 2-of-2 script, both key hashes, and the script address.",
  "artifact.description.multisigUtxos": "Current script state according to Blockfrost Preprod.",
  "artifact.description.lockDetails": "Shows the script address, signers, amount, and calculated body.",
  "artifact.description.unlockDetails": "Shows the consumed UTxO, destination, signers, and script change.",
  "artifact.description.receivedWitness": "Signer A pastes the witness returned by signer B here.",
  "artifact.description.currentWitness": "Signer B copies this witness and sends it to signer A.",
  "artifact.description.eacDetails": "Includes the policy ID, stable script, label 65536, payload, and transaction summary.",
  "artifact.description.retireDetails": "Includes the policy ID, burn, remaining balance, and retirement references.",
  "artifact.description.mintDetails": "Includes the policy ID, script, validity, metadata under label 721, and transaction summary.",
  "multisig.status.initial": "Connect signer A and enter signer B's address.",
  "multisig.status.invalidated": "The multisig setup was invalidated because the signers changed.",
  "multisig.status.signerChanged": "Signer A changed. Generate and review the 2-of-2 script again.",
  "multisig.status.connectAgain": "Reconnect signer A and generate the 2-of-2 script.",
  "multisig.status.generating": "Generating the 2-of-2 script...",
  "multisig.status.generated": "Script created. Open the details and check the address and hashes before authorizing the lock.",
  "multisig.status.listing": "Querying script UTxOs on Preprod...",
  "multisig.status.none": "No UTxO indexed yet. If the lock was just included, wait a few seconds and try again.",
  "multisig.status.one": "The only UTxO was selected: {outRef}",
  "multisig.status.many": "Several UTxOs are available. Explicitly choose which one the unlock should consume.",
  "multisig.status.waitCurrent": "Wait for the current step to finish before starting multisig setup.",
  "multisig.status.recover": "Correct the indicated problem and repeat this step.",
  "multisig.error.generic": "The multisig step could not be completed",
  "multisig.guidance.generic": "Check both wallets, the Preprod network, and the addresses. Then try again.",
  "multisig.guidance.retry": "Try again.",
  "multisig.choice.label": "{outRef} | {lovelace} lovelace",
  "multisig.log.generated": "Multisig: 2-of-2 script generated with two distinct keys.",
  "multisig.log.failed": "The multisig setup step failed.",
  "multisig.error.setupRequired": "Generate and confirm the multisig setup again before continuing",
  "multisig.error.walletMismatch": "The connected wallet does not match the key that built this transaction",
  "multisig.error.contextMissing": "The CBOR does not provide a script address and UTxO for verification",
  "multisig.error.notRequiredSigner": "The connected wallet is not one of the required signers for this unlock",
  "session.description": "Saved in this tab at {savedAt}. The wallet and multisig setup must be validated again.",
  "session.log.busy": "Wait for the current step to finish before restoring the session.",
  "session.log.restored": "Session restored. Reconnect the wallet before signing or building.",
  "session.log.discarded": "Saved session discarded.",
  "technicalLog.newError.one": "New error in the technical log.",
  "technicalLog.newError.other": "{count} unread errors in the technical log.",
  "technicalLog.open": "Open technical log",
  "technicalLog.openUnread.one": "Open technical log, 1 unread error",
  "technicalLog.openUnread.other": "Open technical log, {count} unread errors",
} as const satisfies Record<keyof typeof portugueseFlowMessages, string>
