export const portugueseStaticMessages = {
  "page.title": "Cardano Technical Workshop",
  "hero.eyebrow": "Cardano Technical Workshop",
  "hero.title": "Workbench de transações Cardano",
  "hero.lead": "Construa, assine, inspecione e submeta transações na Cardano Preprod.",
  "language.selector.label": "Idioma",
  "language.portuguese": "Português",
  "language.english": "English",
  "network.label": "Rede",
  "network.name": "Preprod",
  "network.detail": "tADA e taxas reais de testnet",
  "network.ariaLabel": "Rede usada pela Workbench",
  "common.exercise": "Exercício",
  "common.objective": "Objetivo",
  "common.completedWhen": "Concluído quando",
  "common.submissionEffect": "Efeito da submissão",
  "common.risk": "Risco",
  "common.limit": "Limite",
  "common.build": "Construir",
  "common.sign": "Assinar",
  "common.attach": "Anexar",
  "common.submit": "Submeter",
  "common.confirm": "Confirmar",
  "common.technicalDetail": "Detalhe técnico",
  "common.reviewBeforeSubmission": "Revisão antes da submissão",
  "common.checkInclusion": "Verificar inclusão",
  "common.viewCardanoscan": "Ver no Cardanoscan",
  "common.tryAgain": "Tentar novamente",
  "common.resetExercise": "Reiniciar exercício",
  "common.signWithWallet": "2. Assinar com a wallet",
  "common.attachWitness": "3. Anexar witness",
  "common.recipientPreprod": "Destinatário Preprod",
  "common.lovelaceAmount": "Valor em lovelace",
  "common.addressPlaceholder": "addr_test...",
  "readiness.eyebrow": "Antes de começar",
  "readiness.title": "Prepare o ambiente",
  "readiness.description": "A construção usa o backend local e o Blockfrost. A chave privada permanece na extensão CIP-30.",
  "readiness.setup.summary": "Primeira execução local: instalar e iniciar",
  "readiness.setup.step1.before": "No terminal, entre na pasta do workshop e execute",
  "readiness.setup.step2.before": "Execute",
  "readiness.setup.step2.after": "e coloque no arquivo somente o project id de um projeto Blockfrost Preprod.",
  "readiness.setup.step3.before": "Carregue o ambiente com",
  "readiness.setup.step4.after": "e mantenha o terminal aberto.",
  "readiness.setup.step5": "Volte a esta página. A verificação será repetida ao recarregar.",
  "readiness.setup.warning": "Não informe seed phrase, chave privada ou credencial Blockfrost nesta página.",
  "readiness.inspector.ariaLabel": "Ferramenta externa para inspeção de CBOR",
  "readiness.inspector.title": "Inspecione os artefatos CBOR",
  "readiness.inspector.description": "Use o CBOR Nemo para decodificar o unsigned CBOR produzido nos exercícios.",
  "readiness.inspector.warning": "Ferramenta de terceiros. Não informe seed phrase, chave privada ou credencial Blockfrost. Quem obtiver um signed CBOR válido poderá submetê-lo à rede.",
  "readiness.inspector.open": "Abrir CBOR Nemo",
  "readiness.list.ariaLabel": "Estado dos pré-requisitos",
  "readiness.backend.title": "Backend local",
  "readiness.backend.help.before": "Inicie com",
  "readiness.provider.title": "Blockfrost Preprod",
  "readiness.provider.help.before": "O backend precisa de",
  "readiness.walletExtension.title": "Wallet CIP-30",
  "readiness.walletExtension.help": "Instale e desbloqueie uma extensão compatível.",
  "readiness.walletNetwork.title": "Wallet em testnet",
  "readiness.walletNetwork.help": "Selecione Preprod na extensão antes de conectar.",
  "readiness.walletFunding.title": "Saldo de tADA",
  "readiness.walletFunding.help": "A wallet precisa de ao menos um UTxO na Preprod para construir transações.",
  "readiness.wallet.label": "Wallet detectada",
  "readiness.wallet.searching": "Procurando extensões...",
  "readiness.wallet.connect": "Conectar wallet",
  "readiness.wallet.help.beforeAddress": "O identificador CIP-30 confirma testnet, mas não distingue Preprod de Preview. Confira o nome da rede na extensão. Sem saldo, copie seu",
  "readiness.wallet.help.beforeFaucet": ", abra o",
  "readiness.wallet.help.faucet": "faucet oficial",
  "readiness.wallet.help.afterFaucet": ", selecione Pre-production e solicite test ada. Depois, reconecte para repetir a verificação.",
  "readiness.wallet.noneConnected": "Nenhuma wallet conectada.",
  "readiness.checking": "Verificando o ambiente...",
  "session.available": "Há uma sessão desta aba para continuar.",
  "session.description": "Os campos e artefatos das transações foram preservados. A wallet e o setup multisig deverão ser validados novamente.",
  "session.resume": "Continuar sessão",
  "session.discard": "Descartar",
  "nav.ariaLabel": "Exercícios da Workbench",
  "nav.payment": "Pagamento",
  "nav.metadata": "Metadata",
  "nav.multisig": "Multisig",
  "nav.eacRaw": "EAC raw",
  "nav.cip25": "CIP-25",
  "payment.title": "Pagamento simples",
  "payment.description": "Envie tADA e acompanhe o corpo sem assinatura, o witness, a transação assinada e a inclusão em bloco.",
  "payment.objective": "Enviar uma quantidade definida de lovelace para outro endereço.",
  "payment.completedWhen": "O hash aparecer como incluído em um bloco da Preprod.",
  "payment.effect": "Gasta tADA e taxa da wallet conectada. Depois de incluída, a transferência não pode ser desfeita.",
  "payment.lovelaceHelp": "1 ADA equivale a 1.000.000 lovelace.",
  "payment.progress.ariaLabel": "Progresso do pagamento",
  "payment.progress.build": "O backend consulta UTxOs e calcula inputs, outputs, taxa e troco.",
  "payment.progress.sign": "A extensão mostra a transação e produz um witness sem expor a chave.",
  "payment.progress.attach": "A Workbench valida o witness contra o corpo e cria o signed CBOR.",
  "payment.progress.submit": "Revise o efeito e envie a transação assinada à Preprod.",
  "payment.progress.confirm": "Verifique se o hash foi incluído em um bloco.",
  "payment.action.build": "1. Construir unsigned tx",
  "payment.review.summary": "Construa e assine a transação para ver o resumo.",
  "payment.acknowledgement": "Conferi destinatário, valor e rede. Entendo que a submissão transfere tADA na Preprod.",
  "payment.action.submit": "4. Submeter na Preprod",
  "metadata.title": "Pagamento com metadata",
  "metadata.description": "Envie tADA e publique uma mensagem no label 674 na mesma transação.",
  "metadata.objective": "Relacionar uma mensagem pública a uma transação de pagamento.",
  "metadata.completedWhen": "A transação estiver incluída e o label 674 puder ser inspecionado.",
  "metadata.effect": "Transfere tADA e publica a mensagem permanentemente. Não use dados pessoais ou sigilosos.",
  "metadata.message.label": "Mensagem pública",
  "metadata.message.help": "O conteúdo ficará visível na blockchain.",
  "metadata.progress.ariaLabel": "Progresso da transação com metadata",
  "metadata.progress.build": "O backend anexa o label 674 e calcula a transação.",
  "metadata.progress.sign": "A wallet autoriza a transação exata.",
  "metadata.progress.attach": "O witness validado vira parte do signed CBOR.",
  "metadata.progress.submit": "A mensagem e o pagamento são enviados à Preprod.",
  "metadata.progress.confirm": "Verifique inclusão e metadata no explorador.",
  "metadata.action.build": "1. Construir tx com metadata",
  "metadata.review.acknowledgement": "Conferi destinatário, valor e mensagem pública. Entendo que a metadata ficará visível na Preprod.",
  "multisig.title": "Multisig 2-de-2",
  "multisig.description": "Duas chaves de pagamento diferentes precisam assinar o mesmo unsigned CBOR para movimentar o saldo do script.",
  "multisig.objective": "Criar um script 2-de-2, bloquear tADA e desbloquear com dois witnesses.",
  "multisig.completedWhen": "O unlock estiver incluído. O valor escolhido vai ao destino e o troco volta ao script.",
  "multisig.risk": "Se uma chave estiver errada ou indisponível, o saldo bloqueado pode ficar inacessível.",
  "multisig.setup.title": "Defina os dois signers",
  "multisig.setup.description": "Signer A é a wallet conectada. Signer B fornece outro endereço controlado por uma chave de pagamento diferente.",
  "multisig.setup.signerBLabel": "Endereço do signer B",
  "multisig.setup.generate": "Gerar script address",
  "multisig.setup.listUtxos": "Listar UTxOs do script",
  "multisig.setup.status": "Conecte o signer A e informe o endereço do signer B.",
  "multisig.setup.acknowledgement": "Conferi script address e as duas payment key hashes. Vou usar exatamente essas duas wallets no lock e no unlock.",
  "multisig.setup.chooseUtxo": "Escolha o UTxO a consumir",
  "multisig.lock.title": "Bloqueie tADA no script",
  "multisig.lock.amountLabel": "Valor para lock",
  "multisig.lock.progress.ariaLabel": "Progresso do lock multisig",
  "multisig.lock.progress.build": "Cria um output no script address.",
  "multisig.lock.progress.sign": "Signer A autoriza o gasto de seus inputs.",
  "multisig.lock.progress.attach": "O witness de A é validado e anexado.",
  "multisig.lock.progress.submit": "Move tADA para o script 2-de-2.",
  "multisig.lock.progress.confirm": "Depois da inclusão, liste os UTxOs do script.",
  "multisig.lock.action.build": "1. Construir lock tx",
  "multisig.lock.action.sign": "2. Assinar lock",
  "multisig.lock.review.title": "Revisão do lock",
  "multisig.lock.review.summary": "Construa e assine o lock para ver o resumo.",
  "multisig.lock.acknowledgement": "Conferi os dois signers e o valor. Entendo que ambos serão necessários para recuperar o saldo.",
  "multisig.lock.action.submit": "4. Submeter lock",
  "multisig.lock.reset": "Reiniciar lock local",
  "multisig.unlock.title": "Compartilhe, assine e desbloqueie",
  "multisig.unlock.handoff.1": "Signer A lista e escolhe o UTxO, depois constrói o unlock.",
  "multisig.unlock.handoff.2": "Signer A assina e envia somente o unsigned CBOR ao signer B.",
  "multisig.unlock.handoff.3": "Signer B abre a Workbench, conecta sua wallet, cola o unsigned CBOR, assina e devolve seu witness.",
  "multisig.unlock.handoff.4": "Signer A cola o witness recebido, anexa os dois e submete.",
  "multisig.unlock.destinationLabel": "Destino do unlock",
  "multisig.unlock.amountLabel": "Valor para unlock",
  "multisig.unlock.utxoLabel": "UTxO do script",
  "multisig.unlock.utxoPlaceholder": "txhash#index",
  "multisig.unlock.utxoHelp": "Use “Listar UTxOs do script”. Se o lock acabou de ser incluído, aguarde a indexação.",
  "multisig.unlock.progress.ariaLabel": "Progresso do unlock multisig",
  "multisig.unlock.progress.buildTitle": "Construir ou importar",
  "multisig.unlock.progress.build": "Todos os signers devem assinar o mesmo unsigned CBOR.",
  "multisig.unlock.progress.collectTitle": "Coletar duas assinaturas",
  "multisig.unlock.progress.collect": "Cada witness deve corresponder a uma das chaves exigidas.",
  "multisig.unlock.progress.attach": "A Workbench valida assinaturas, signers e corpo da transação.",
  "multisig.unlock.progress.submit": "Consome o UTxO escolhido e devolve o troco ao script.",
  "multisig.unlock.progress.confirm": "Verifique se o unlock foi incluído em um bloco da Preprod.",
  "multisig.unlock.signReview.title": "Revisão obrigatória antes de assinar",
  "multisig.unlock.signReview.summary": "Construa ou cole o unsigned CBOR para inspecionar UTxO, destino, valor, troco e signers.",
  "multisig.unlock.signReview.acknowledgement": "Conferi os dados derivados do CBOR e reconheço este unlock como a transação combinada entre os dois signers.",
  "multisig.unlock.action.build": "1. Construir unlock tx",
  "multisig.unlock.action.sign": "2. Assinar CBOR revisado",
  "multisig.unlock.action.attach": "3. Anexar os dois witnesses",
  "multisig.unlock.review.title": "Revisão do unlock",
  "multisig.unlock.review.summary": "Construa, colete e anexe os witnesses para ver o resumo.",
  "multisig.unlock.acknowledgement": "Conferi UTxO, destino, valor e os dois signers. Entendo que o UTxO será consumido e o troco voltará ao script.",
  "multisig.unlock.action.submit": "4. Submeter unlock",
  "multisig.unlock.reset": "Reiniciar unlock local",
  "eac.title": "Ciclo EAC: emissão e aposentadoria",
  "eac.description": "Execute um exemplo Cardano inspirado no caso Brevik. A quantidade é ilustrativa e não representa a oferta alocável publicada pela Heidelberg Materials.",
  "eac.objective": "Emitir 12088322 unidades ilustrativas, aposentar 125000 e reconstruir o saldo restante de 11963322 unidades.",
  "eac.completedWhen": "Mint e burn estiverem incluídos, com as referências externas no label 65536 e as quantidades no ledger.",
  "eac.boundary": "A API valida o schema. A policy verifica somente a chave; não lê a metadata, não limita a oferta e não prova os fatos industriais.",
  "eac.spec.ariaLabel": "Parâmetros fixos da emissão EAC",
  "eac.spec.assetName": "Asset name",
  "eac.spec.illustrativeQuantity": "Quantidade ilustrativa on-chain",
  "eac.spec.display": "Exibição",
  "eac.spec.displayValue": "12.088,322 EAC",
  "eac.spec.metadataLabel": "Metadata label",
  "eac.spec.metadataNote": ", private use CIP-10. A metadata continua pública.",
  "eac.recipient.label": "Endereço contábil que receberá o saldo",
  "eac.recipient.placeholder": "Conecte a wallet",
  "eac.recipient.help": "O saldo permanece na wallet conectada para que ela possa construir o burn posterior.",
  "eac.metadata.label": "Metadata JSON de emissão",
  "eac.metadata.help": "Os três hashes preenchidos são valores sintéticos de exemplo, não evidências reais da Heidelberg Materials ou da DNV. Use somente hexadecimal minúsculo com 64 caracteres.",
  "eac.progress.ariaLabel": "Progresso da emissão EAC",
  "eac.progress.build": "Cria a policy estável, o mint, o output e a metadata raw.",
  "eac.progress.sign": "A wallet satisfaz a chave exigida pela policy.",
  "eac.progress.attach": "Valida e adiciona o witness à emissão.",
  "eac.progress.submit": "Publica a emissão e as referências na Preprod.",
  "eac.progress.confirm": "Verifique campo mint, output e label 65536.",
  "eac.action.build": "1. Construir emissão EAC",
  "eac.review.summary": "Construa e assine a emissão EAC para ver o resumo.",
  "eac.acknowledgement": "Conferi endereço contábil, quantidade, policy, validade e referências. Entendo que a policy não valida a metadata nem os fatos industriais externos.",
  "eac.action.submit": "4. Submeter emissão",
  "eac.reset": "Reiniciar emissão",
  "retire.title": "Aposente 125,000 EAC",
  "retire.description": "Depois que a emissão estiver incluída e indexada, queime 125000 unidades e mantenha 11963322 unidades na wallet contábil.",
  "retire.spec.ariaLabel": "Parâmetros fixos da aposentadoria EAC",
  "retire.spec.burn": "Burn",
  "retire.spec.retiredDisplay": "Exibição aposentada",
  "retire.spec.retiredValue": "125,000 EAC",
  "retire.spec.remainingBalance": "Saldo restante",
  "retire.spec.remainingValue": "11.963,322 EAC",
  "retire.metadata.label": "Metadata JSON de aposentadoria",
  "retire.metadata.help": "Hashes sintéticos do exercício. Quantidade, ação e asset name permanecem fora da metadata.",
  "retire.progress.ariaLabel": "Progresso da aposentadoria EAC",
  "retire.progress.build": "Localiza o saldo da wallet, cria o burn e devolve o restante.",
  "retire.progress.sign": "A mesma chave satisfaz a policy estável.",
  "retire.progress.attach": "Valida e adiciona o witness à aposentadoria.",
  "retire.progress.submit": "Publica o burn e as referências externas.",
  "retire.progress.confirm": "Verifique burn, saldo restante e label 65536.",
  "retire.action.build": "1. Construir aposentadoria",
  "retire.review.title": "Revisão da aposentadoria",
  "retire.review.summary": "Construa e assine a aposentadoria EAC para ver o resumo.",
  "retire.acknowledgement": "Conferi burn, saldo restante, policy e referências. Entendo que a rede não prova a entrega nem a declaração.",
  "retire.action.submit": "4. Submeter aposentadoria",
  "retire.reset": "Reiniciar aposentadoria",
  "mint.title": "Media token com CIP-25",
  "mint.description": "Crie um asset nativo com metadata de apresentação padronizada pela CIP-25 no label 721.",
  "mint.objective": "Emitir um media token com policy nativa e metadata de nome, imagem e descrição.",
  "mint.completedWhen": "A transação estiver incluída e o asset puder ser localizado pelo policy id.",
  "mint.effect": "Cria unidades de um asset na Preprod, usa ao menos 5 tADA no output e paga taxa. A policy expira em cerca de três horas.",
  "mint.recipient.label": "Endereço que receberá o asset",
  "mint.assetName.label": "Asset name",
  "mint.amount.label": "Quantidade",
  "mint.metadataName.label": "Nome na metadata",
  "mint.image.label": "Image URI",
  "mint.description.label": "Description",
  "mint.fields.help": "Campos CIP-25 acima de 64 bytes são divididos quando permitido; o nome da metadata precisa caber em 64 bytes.",
  "mint.progress.ariaLabel": "Progresso do mint",
  "mint.progress.build": "Cria policy, asset, metadata, validade e output do mint.",
  "mint.progress.sign": "A wallet satisfaz o required signer da policy.",
  "mint.progress.attach": "Valida e adiciona o witness ao mint.",
  "mint.progress.submit": "Publica o mint e a metadata na Preprod.",
  "mint.progress.confirm": "Verifique inclusão, policy id e asset name.",
  "mint.action.build": "1. Construir mint tx",
  "mint.review.summary": "Construa e assine o mint para ver o resumo.",
  "mint.acknowledgement": "Conferi destinatário, quantidade, policy e validade. Entendo que a submissão cria o asset e paga taxa na Preprod.",
  "mint.action.submit": "4. Submeter mint",
  "log.open.ariaLabel": "Abrir log técnico",
  "log.title": "Log técnico",
  "log.description": "Eventos desta aba em ordem cronológica.",
  "log.close": "Fechar",
  "log.entries.ariaLabel": "Eventos técnicos da Workbench",
  "artifact.copy": "Copiar",
  "artifact.payment.details.title": "Detalhes da construção",
  "artifact.payment.details.description": "Compare destinatário e valor informados com inputs, outputs, taxa e troco calculados.",
  "artifact.payment.unsigned.title": "Unsigned tx CBOR",
  "artifact.payment.unsigned.description": "Corpo ainda sem autorização da wallet.",
  "artifact.payment.witness.title": "Witness set CBOR",
  "artifact.payment.witness.description": "Assinatura específica para este corpo de transação.",
  "artifact.payment.signed.title": "Signed tx CBOR",
  "artifact.payment.signed.description": "Transação pronta para revisão e submissão.",
  "artifact.payment.hash.title": "Tx hash",
  "artifact.payment.hash.description": "Identificador usado para acompanhar a inclusão na rede.",
  "artifact.metadata.details.title": "Detalhes e metadata",
  "artifact.metadata.details.description": "Mostra label, mensagem e resumo do corpo da transação.",
  "artifact.metadata.unsigned.title": "Unsigned tx CBOR",
  "artifact.metadata.unsigned.description": "Transação com metadata antes da assinatura.",
  "artifact.metadata.witness.title": "Witness set CBOR",
  "artifact.metadata.witness.description": "Assinatura retornada pela wallet.",
  "artifact.metadata.signed.title": "Signed tx CBOR",
  "artifact.metadata.signed.description": "Transação com metadata e witness anexado.",
  "artifact.metadata.hash.title": "Tx hash",
  "artifact.metadata.hash.description": "Identificador para verificar inclusão e metadata.",
  "artifact.multisig.details.title": "Native script e endereço",
  "artifact.multisig.details.description": "Inclui script 2-de-2, hashes das duas chaves e script address.",
  "artifact.multisig.utxos.title": "UTxOs disponíveis",
  "artifact.multisig.utxos.description": "Estado atual do script segundo o Blockfrost Preprod.",
  "artifact.multisig.lock.details.title": "Detalhes do lock",
  "artifact.multisig.lock.details.description": "Mostra script address, signers, valor e corpo calculado.",
  "artifact.multisig.lock.unsigned.title": "Unsigned lock tx CBOR",
  "artifact.multisig.lock.unsigned.description": "Transação que cria o UTxO no script.",
  "artifact.multisig.lock.witness.title": "Witness do lock",
  "artifact.multisig.lock.witness.description": "Assinatura de A para os inputs do lock.",
  "artifact.multisig.lock.signed.title": "Signed lock tx CBOR",
  "artifact.multisig.lock.signed.description": "Lock pronto para submissão.",
  "artifact.multisig.lock.hash.title": "Lock tx hash",
  "artifact.multisig.lock.hash.description": "Use este hash para acompanhar a inclusão.",
  "artifact.multisig.unlock.details.title": "Detalhes do unlock",
  "artifact.multisig.unlock.details.description": "Mostra UTxO consumido, destino, signers e troco do script.",
  "artifact.multisig.unlock.unsigned.title": "Unsigned unlock tx CBOR",
  "artifact.multisig.unlock.unsigned.description": "Signer A envia este CBOR ao signer B. Signer B pode colar aqui.",
  "artifact.multisig.unlock.currentWitness.title": "Witness da wallet atual",
  "artifact.multisig.unlock.currentWitness.description": "Signer B copia este witness e o envia ao signer A.",
  "artifact.multisig.unlock.receivedWitness.title": "Witness recebido",
  "artifact.multisig.unlock.receivedWitness.description": "Signer A cola aqui o witness devolvido pelo signer B.",
  "artifact.multisig.unlock.signed.title": "Signed unlock tx CBOR",
  "artifact.multisig.unlock.signed.description": "Só é criado após validar as duas assinaturas exigidas.",
  "artifact.multisig.unlock.hash.title": "Unlock tx hash",
  "artifact.multisig.unlock.hash.description": "Identificador do unlock submetido.",
  "artifact.eac.details.title": "Policy, asset e metadata raw",
  "artifact.eac.details.description": "Inclui policy id, script estável, label 65536, payload e resumo da transação.",
  "artifact.eac.unsigned.title": "Unsigned EAC tx CBOR",
  "artifact.eac.unsigned.description": "Emissão antes da autorização da wallet.",
  "artifact.eac.witness.title": "Witness set CBOR",
  "artifact.eac.witness.description": "Assinatura da chave exigida pela policy.",
  "artifact.eac.signed.title": "Signed EAC tx CBOR",
  "artifact.eac.signed.description": "Emissão pronta para submissão dentro da validade da transação.",
  "artifact.eac.hash.title": "Tx hash",
  "artifact.eac.hash.description": "Identificador para verificar quantidade, output e metadata.",
  "artifact.retire.details.title": "Policy, burn e metadata",
  "artifact.retire.details.description": "Inclui policy id, burn, saldo restante e referências de aposentadoria.",
  "artifact.retire.unsigned.title": "Unsigned retirement tx CBOR",
  "artifact.retire.unsigned.description": "Aposentadoria antes da autorização da wallet.",
  "artifact.retire.witness.title": "Witness set CBOR",
  "artifact.retire.witness.description": "Assinatura da chave exigida pela policy.",
  "artifact.retire.signed.title": "Signed retirement tx CBOR",
  "artifact.retire.signed.description": "Burn pronto para submissão.",
  "artifact.retire.hash.title": "Retirement tx hash",
  "artifact.retire.hash.description": "Identificador para verificar burn, saldo e metadata.",
  "artifact.mint.details.title": "Policy, asset e metadata",
  "artifact.mint.details.description": "Inclui policy id, script, validade, metadata 721 e resumo da transação.",
  "artifact.mint.unsigned.title": "Unsigned mint tx CBOR",
  "artifact.mint.unsigned.description": "Mint antes da autorização da wallet.",
  "artifact.mint.witness.title": "Witness set CBOR",
  "artifact.mint.witness.description": "Assinatura da chave exigida pela policy.",
  "artifact.mint.signed.title": "Signed mint tx CBOR",
  "artifact.mint.signed.description": "Mint pronto para submissão enquanto a policy estiver válida.",
  "artifact.mint.hash.title": "Tx hash",
  "artifact.mint.hash.description": "Identificador para verificar o asset na Preprod.",
} as const

export const englishStaticMessages = {
  "page.title": "Cardano Technical Workshop",
  "hero.eyebrow": "Cardano Technical Workshop",
  "hero.title": "Cardano transaction Workbench",
  "hero.lead": "Build, sign, inspect, and submit transactions on Cardano Preprod.",
  "language.selector.label": "Language",
  "language.portuguese": "Portuguese",
  "language.english": "English",
  "network.label": "Network",
  "network.name": "Preprod",
  "network.detail": "tADA and testnet transaction fees",
  "network.ariaLabel": "Network used by the Workbench",
  "common.exercise": "Exercise",
  "common.objective": "Objective",
  "common.completedWhen": "Completion condition",
  "common.submissionEffect": "Submission effect",
  "common.risk": "Risk",
  "common.limit": "Boundary",
  "common.build": "Build",
  "common.sign": "Sign",
  "common.attach": "Attach",
  "common.submit": "Submit",
  "common.confirm": "Confirm",
  "common.technicalDetail": "Technical details",
  "common.reviewBeforeSubmission": "Review before submission",
  "common.checkInclusion": "Check inclusion",
  "common.viewCardanoscan": "View on Cardanoscan",
  "common.tryAgain": "Try again",
  "common.resetExercise": "Reset exercise",
  "common.signWithWallet": "2. Sign with the wallet",
  "common.attachWitness": "3. Attach witness",
  "common.recipientPreprod": "Preprod recipient",
  "common.lovelaceAmount": "Amount in lovelace",
  "common.addressPlaceholder": "addr_test...",
  "readiness.eyebrow": "Before you begin",
  "readiness.title": "Prepare the environment",
  "readiness.description": "Transaction building uses the local backend and Blockfrost. The private key remains in the CIP-30 extension.",
  "readiness.setup.summary": "First local run: install and start",
  "readiness.setup.step1.before": "In the terminal, open the workshop directory and run",
  "readiness.setup.step2.before": "Run",
  "readiness.setup.step2.after": "and add only the project ID for a Blockfrost Preprod project to the file.",
  "readiness.setup.step3.before": "Load the environment with",
  "readiness.setup.step4.after": "and keep the terminal open.",
  "readiness.setup.step5": "Return to this page. The check will run again when you reload it.",
  "readiness.setup.warning": "Do not enter a seed phrase, private key, or Blockfrost credential on this page.",
  "readiness.inspector.ariaLabel": "External tool for CBOR inspection",
  "readiness.inspector.title": "Inspect the CBOR artifacts",
  "readiness.inspector.description": "Use CBOR Nemo to decode the unsigned CBOR produced in the exercises.",
  "readiness.inspector.warning": "Third-party tool. Do not enter a seed phrase, private key, or Blockfrost credential. Anyone who obtains a valid signed CBOR can submit it to the network.",
  "readiness.inspector.open": "Open CBOR Nemo",
  "readiness.list.ariaLabel": "Prerequisite status",
  "readiness.backend.title": "Local backend",
  "readiness.backend.help.before": "Start it with",
  "readiness.provider.title": "Blockfrost Preprod",
  "readiness.provider.help.before": "The backend requires",
  "readiness.walletExtension.title": "CIP-30 wallet",
  "readiness.walletExtension.help": "Install and unlock a compatible extension.",
  "readiness.walletNetwork.title": "Wallet on testnet",
  "readiness.walletNetwork.help": "Select Preprod in the extension before connecting.",
  "readiness.walletFunding.title": "tADA balance",
  "readiness.walletFunding.help": "The wallet needs at least one UTxO on Preprod to build transactions.",
  "readiness.wallet.label": "Detected wallet",
  "readiness.wallet.searching": "Looking for extensions...",
  "readiness.wallet.connect": "Connect wallet",
  "readiness.wallet.help.beforeAddress": "The CIP-30 network ID confirms testnet, but does not distinguish Preprod from Preview. Check the network name in the extension. If the wallet has no balance, copy its",
  "readiness.wallet.help.beforeFaucet": ", open the",
  "readiness.wallet.help.faucet": "official faucet",
  "readiness.wallet.help.afterFaucet": ", select Pre-production, and request test ada. Then reconnect to run the check again.",
  "readiness.wallet.noneConnected": "No wallet connected.",
  "readiness.checking": "Checking the environment...",
  "session.available": "A session from this tab can be continued.",
  "session.description": "The transaction fields and artifacts were preserved. The wallet and multisig setup must be validated again.",
  "session.resume": "Continue session",
  "session.discard": "Discard",
  "nav.ariaLabel": "Workbench exercises",
  "nav.payment": "Payment",
  "nav.metadata": "Metadata",
  "nav.multisig": "Multisig",
  "nav.eacRaw": "Raw EAC",
  "nav.cip25": "CIP-25",
  "payment.title": "Simple payment",
  "payment.description": "Send tADA and inspect the unsigned body, witness, signed transaction, and block inclusion.",
  "payment.objective": "Send a specified amount of lovelace to another address.",
  "payment.completedWhen": "The hash is shown as included in a Preprod block.",
  "payment.effect": "Spends tADA and a fee from the connected wallet. Once included, the transfer cannot be reversed.",
  "payment.lovelaceHelp": "1 ADA equals 1,000,000 lovelace.",
  "payment.progress.ariaLabel": "Payment progress",
  "payment.progress.build": "The backend queries UTxOs and calculates inputs, outputs, the fee, and change.",
  "payment.progress.sign": "The extension displays the transaction and produces a witness without exposing the key.",
  "payment.progress.attach": "The Workbench validates the witness against the body and creates the signed CBOR.",
  "payment.progress.submit": "Review the effect and send the signed transaction to Preprod.",
  "payment.progress.confirm": "Check whether the hash was included in a block.",
  "payment.action.build": "1. Build unsigned tx",
  "payment.review.summary": "Build and sign the transaction to see the summary.",
  "payment.acknowledgement": "I checked the recipient, amount, and network. I understand that submission transfers tADA on Preprod.",
  "payment.action.submit": "4. Submit to Preprod",
  "metadata.title": "Payment with metadata",
  "metadata.description": "Send tADA and publish a message under label 674 in the same transaction.",
  "metadata.objective": "Associate a public message with a payment transaction.",
  "metadata.completedWhen": "The transaction is included and label 674 can be inspected.",
  "metadata.effect": "Transfers tADA and publishes the message permanently. Do not use personal or confidential data.",
  "metadata.message.label": "Public message",
  "metadata.message.help": "The content will be visible on the blockchain.",
  "metadata.progress.ariaLabel": "Metadata transaction progress",
  "metadata.progress.build": "The backend attaches label 674 and calculates the transaction.",
  "metadata.progress.sign": "The wallet authorizes the exact transaction.",
  "metadata.progress.attach": "The validated witness becomes part of the signed CBOR.",
  "metadata.progress.submit": "The message and payment are sent to Preprod.",
  "metadata.progress.confirm": "Check inclusion and metadata in the explorer.",
  "metadata.action.build": "1. Build tx with metadata",
  "metadata.review.acknowledgement": "I checked the recipient, amount, and public message. I understand that the metadata will be visible on Preprod.",
  "multisig.title": "2-of-2 multisig",
  "multisig.description": "Two different payment keys must sign the same unsigned CBOR to move the script balance.",
  "multisig.objective": "Create a 2-of-2 script, lock tADA, and unlock it with two witnesses.",
  "multisig.completedWhen": "The unlock is included. The selected amount goes to the destination and the change returns to the script.",
  "multisig.risk": "If either key is incorrect or unavailable, the locked balance may become inaccessible.",
  "multisig.setup.title": "Define the two signers",
  "multisig.setup.description": "Signer A is the connected wallet. Signer B provides another address controlled by a different payment key.",
  "multisig.setup.signerBLabel": "Signer B address",
  "multisig.setup.generate": "Generate script address",
  "multisig.setup.listUtxos": "List script UTxOs",
  "multisig.setup.status": "Connect signer A and enter signer B’s address.",
  "multisig.setup.acknowledgement": "I checked the script address and both payment key hashes. I will use these exact two wallets for the lock and unlock.",
  "multisig.setup.chooseUtxo": "Choose the UTxO to consume",
  "multisig.lock.title": "Lock tADA in the script",
  "multisig.lock.amountLabel": "Amount to lock",
  "multisig.lock.progress.ariaLabel": "Multisig lock progress",
  "multisig.lock.progress.build": "Creates an output at the script address.",
  "multisig.lock.progress.sign": "Signer A authorizes spending the selected inputs.",
  "multisig.lock.progress.attach": "Signer A’s witness is validated and attached.",
  "multisig.lock.progress.submit": "Moves tADA to the 2-of-2 script.",
  "multisig.lock.progress.confirm": "After inclusion, list the script UTxOs.",
  "multisig.lock.action.build": "1. Build lock tx",
  "multisig.lock.action.sign": "2. Sign lock",
  "multisig.lock.review.title": "Lock review",
  "multisig.lock.review.summary": "Build and sign the lock to see the summary.",
  "multisig.lock.acknowledgement": "I checked both signers and the amount. I understand that both will be required to recover the balance.",
  "multisig.lock.action.submit": "4. Submit lock",
  "multisig.lock.reset": "Reset local lock",
  "multisig.unlock.title": "Share, sign, and unlock",
  "multisig.unlock.handoff.1": "Signer A lists and selects the UTxO, then builds the unlock.",
  "multisig.unlock.handoff.2": "Signer A signs and sends only the unsigned CBOR to signer B.",
  "multisig.unlock.handoff.3": "Signer B opens the Workbench, connects their wallet, pastes the unsigned CBOR, signs, and returns their witness.",
  "multisig.unlock.handoff.4": "Signer A pastes the received witness, attaches both witnesses, and submits.",
  "multisig.unlock.destinationLabel": "Unlock destination",
  "multisig.unlock.amountLabel": "Amount to unlock",
  "multisig.unlock.utxoLabel": "Script UTxO",
  "multisig.unlock.utxoPlaceholder": "txhash#index",
  "multisig.unlock.utxoHelp": "Use “List script UTxOs”. If the lock was just included, wait for indexing.",
  "multisig.unlock.progress.ariaLabel": "Multisig unlock progress",
  "multisig.unlock.progress.buildTitle": "Build or import",
  "multisig.unlock.progress.build": "All signers must sign the same unsigned CBOR.",
  "multisig.unlock.progress.collectTitle": "Collect two signatures",
  "multisig.unlock.progress.collect": "Each witness must correspond to one of the required keys.",
  "multisig.unlock.progress.attach": "The Workbench validates signatures, signers, and the transaction body.",
  "multisig.unlock.progress.submit": "Consumes the selected UTxO and returns the change to the script.",
  "multisig.unlock.progress.confirm": "Check whether the unlock was included in a Preprod block.",
  "multisig.unlock.signReview.title": "Required review before signing",
  "multisig.unlock.signReview.summary": "Build or paste the unsigned CBOR to inspect the UTxO, destination, amount, change, and signers.",
  "multisig.unlock.signReview.acknowledgement": "I checked the data derived from the CBOR and recognize this unlock as the transaction agreed between both signers.",
  "multisig.unlock.action.build": "1. Build unlock tx",
  "multisig.unlock.action.sign": "2. Sign reviewed CBOR",
  "multisig.unlock.action.attach": "3. Attach both witnesses",
  "multisig.unlock.review.title": "Unlock review",
  "multisig.unlock.review.summary": "Build, collect, and attach the witnesses to see the summary.",
  "multisig.unlock.acknowledgement": "I checked the UTxO, destination, amount, and both signers. I understand that the UTxO will be consumed and the change will return to the script.",
  "multisig.unlock.action.submit": "4. Submit unlock",
  "multisig.unlock.reset": "Reset local unlock",
  "eac.title": "EAC cycle: issuance and retirement",
  "eac.description": "Run a Cardano example inspired by the Brevik case. The quantity is illustrative and does not represent the allocable supply published by Heidelberg Materials.",
  "eac.objective": "Issue 12088322 illustrative units, retire 125000, and reconstruct the remaining balance of 11963322 units.",
  "eac.completedWhen": "The mint and burn are included, with external references under label 65536 and quantities in the ledger.",
  "eac.boundary": "The API validates the schema. The policy checks only the key; it does not read the metadata, cap supply, or prove the industrial facts.",
  "eac.spec.ariaLabel": "Fixed EAC issuance parameters",
  "eac.spec.assetName": "Asset name",
  "eac.spec.illustrativeQuantity": "Illustrative on-chain quantity",
  "eac.spec.display": "Display",
  "eac.spec.displayValue": "12,088.322 EAC",
  "eac.spec.metadataLabel": "Metadata label",
  "eac.spec.metadataNote": ", reserved for private use by CIP-10. The metadata remains public.",
  "eac.recipient.label": "Accounting address that will receive the balance",
  "eac.recipient.placeholder": "Connect the wallet",
  "eac.recipient.help": "The balance remains in the connected wallet so the later burn can use it.",
  "eac.metadata.label": "Issuance metadata JSON",
  "eac.metadata.help": "The three populated hashes are synthetic example values, not actual evidence from Heidelberg Materials or DNV. Use only 64-character lowercase hexadecimal strings.",
  "eac.progress.ariaLabel": "EAC issuance progress",
  "eac.progress.build": "Creates the stable policy, mint, output, and raw metadata.",
  "eac.progress.sign": "The wallet satisfies the key required by the policy.",
  "eac.progress.attach": "Validates and adds the witness to the issuance.",
  "eac.progress.submit": "Publishes the issuance and references on Preprod.",
  "eac.progress.confirm": "Check the mint field, output, and label 65536.",
  "eac.action.build": "1. Build EAC issuance",
  "eac.review.summary": "Build and sign the EAC issuance to see the summary.",
  "eac.acknowledgement": "I checked the accounting address, quantity, policy, validity, and references. I understand that the policy does not validate the metadata or external industrial facts.",
  "eac.action.submit": "4. Submit issuance",
  "eac.reset": "Reset issuance",
  "retire.title": "Retire 125.000 EAC",
  "retire.description": "After the issuance is included and indexed, burn 125000 units and keep 11963322 units in the accounting wallet.",
  "retire.spec.ariaLabel": "Fixed EAC retirement parameters",
  "retire.spec.burn": "Burn",
  "retire.spec.retiredDisplay": "Retired amount",
  "retire.spec.retiredValue": "125.000 EAC",
  "retire.spec.remainingBalance": "Remaining balance",
  "retire.spec.remainingValue": "11,963.322 EAC",
  "retire.metadata.label": "Retirement metadata JSON",
  "retire.metadata.help": "Synthetic hashes for the exercise. Quantity, action, and asset name remain outside the metadata.",
  "retire.progress.ariaLabel": "EAC retirement progress",
  "retire.progress.build": "Locates the wallet balance, creates the burn, and returns the remainder.",
  "retire.progress.sign": "The same key satisfies the stable policy.",
  "retire.progress.attach": "Validates and adds the witness to the retirement.",
  "retire.progress.submit": "Publishes the burn and external references.",
  "retire.progress.confirm": "Check the burn, remaining balance, and label 65536.",
  "retire.action.build": "1. Build retirement",
  "retire.review.title": "Retirement review",
  "retire.review.summary": "Build and sign the EAC retirement to see the summary.",
  "retire.acknowledgement": "I checked the burn, remaining balance, policy, and references. I understand that the network does not prove delivery or the declaration.",
  "retire.action.submit": "4. Submit retirement",
  "retire.reset": "Reset retirement",
  "mint.title": "Media token with CIP-25",
  "mint.description": "Create a native asset with presentation metadata standardized by CIP-25 under label 721.",
  "mint.objective": "Issue a media token with a native policy and name, image, and description metadata.",
  "mint.completedWhen": "The transaction is included and the asset can be found by policy ID.",
  "mint.effect": "Creates units of an asset on Preprod, uses at least 5 tADA in the output, and pays a fee. The policy expires in about three hours.",
  "mint.recipient.label": "Address that will receive the asset",
  "mint.assetName.label": "Asset name",
  "mint.amount.label": "Quantity",
  "mint.metadataName.label": "Metadata name",
  "mint.image.label": "Image URI",
  "mint.description.label": "Description",
  "mint.fields.help": "CIP-25 fields longer than 64 bytes are split where allowed; the metadata name must fit within 64 bytes.",
  "mint.progress.ariaLabel": "Mint progress",
  "mint.progress.build": "Creates the policy, asset, metadata, validity interval, and mint output.",
  "mint.progress.sign": "The wallet satisfies the policy’s required signer.",
  "mint.progress.attach": "Validates and adds the witness to the mint.",
  "mint.progress.submit": "Publishes the mint and metadata on Preprod.",
  "mint.progress.confirm": "Check inclusion, policy ID, and asset name.",
  "mint.action.build": "1. Build mint tx",
  "mint.review.summary": "Build and sign the mint to see the summary.",
  "mint.acknowledgement": "I checked the recipient, quantity, policy, and validity. I understand that submission creates the asset and pays a fee on Preprod.",
  "mint.action.submit": "4. Submit mint",
  "log.open.ariaLabel": "Open technical log",
  "log.title": "Technical log",
  "log.description": "Events from this tab in chronological order.",
  "log.close": "Close",
  "log.entries.ariaLabel": "Workbench technical events",
  "artifact.copy": "Copy",
  "artifact.payment.details.title": "Build details",
  "artifact.payment.details.description": "Compare the recipient and amount entered with the calculated inputs, outputs, fee, and change.",
  "artifact.payment.unsigned.title": "Unsigned tx CBOR",
  "artifact.payment.unsigned.description": "Transaction body not yet authorized by the wallet.",
  "artifact.payment.witness.title": "Witness set CBOR",
  "artifact.payment.witness.description": "Signature specific to this transaction body.",
  "artifact.payment.signed.title": "Signed tx CBOR",
  "artifact.payment.signed.description": "Transaction ready for review and submission.",
  "artifact.payment.hash.title": "Tx hash",
  "artifact.payment.hash.description": "Identifier used to track network inclusion.",
  "artifact.metadata.details.title": "Details and metadata",
  "artifact.metadata.details.description": "Shows the label, message, and transaction body summary.",
  "artifact.metadata.unsigned.title": "Unsigned tx CBOR",
  "artifact.metadata.unsigned.description": "Transaction with metadata before signing.",
  "artifact.metadata.witness.title": "Witness set CBOR",
  "artifact.metadata.witness.description": "Signature returned by the wallet.",
  "artifact.metadata.signed.title": "Signed tx CBOR",
  "artifact.metadata.signed.description": "Transaction with metadata and attached witness.",
  "artifact.metadata.hash.title": "Tx hash",
  "artifact.metadata.hash.description": "Identifier used to check inclusion and metadata.",
  "artifact.multisig.details.title": "Native script and address",
  "artifact.multisig.details.description": "Includes the 2-of-2 script, both key hashes, and the script address.",
  "artifact.multisig.utxos.title": "Available UTxOs",
  "artifact.multisig.utxos.description": "Current script state according to Blockfrost Preprod.",
  "artifact.multisig.lock.details.title": "Lock details",
  "artifact.multisig.lock.details.description": "Shows the script address, signers, amount, and calculated body.",
  "artifact.multisig.lock.unsigned.title": "Unsigned lock tx CBOR",
  "artifact.multisig.lock.unsigned.description": "Transaction that creates the script UTxO.",
  "artifact.multisig.lock.witness.title": "Lock witness",
  "artifact.multisig.lock.witness.description": "Signer A’s signature for the lock inputs.",
  "artifact.multisig.lock.signed.title": "Signed lock tx CBOR",
  "artifact.multisig.lock.signed.description": "Lock ready for submission.",
  "artifact.multisig.lock.hash.title": "Lock tx hash",
  "artifact.multisig.lock.hash.description": "Use this hash to track inclusion.",
  "artifact.multisig.unlock.details.title": "Unlock details",
  "artifact.multisig.unlock.details.description": "Shows the consumed UTxO, destination, signers, and script change.",
  "artifact.multisig.unlock.unsigned.title": "Unsigned unlock tx CBOR",
  "artifact.multisig.unlock.unsigned.description": "Signer A sends this CBOR to signer B. Signer B can paste it here.",
  "artifact.multisig.unlock.currentWitness.title": "Current wallet witness",
  "artifact.multisig.unlock.currentWitness.description": "Signer B copies this witness and sends it to signer A.",
  "artifact.multisig.unlock.receivedWitness.title": "Received witness",
  "artifact.multisig.unlock.receivedWitness.description": "Signer A pastes the witness returned by signer B here.",
  "artifact.multisig.unlock.signed.title": "Signed unlock tx CBOR",
  "artifact.multisig.unlock.signed.description": "Created only after both required signatures are validated.",
  "artifact.multisig.unlock.hash.title": "Unlock tx hash",
  "artifact.multisig.unlock.hash.description": "Identifier of the submitted unlock.",
  "artifact.eac.details.title": "Policy, asset, and raw metadata",
  "artifact.eac.details.description": "Includes the policy ID, stable script, label 65536, payload, and transaction summary.",
  "artifact.eac.unsigned.title": "Unsigned EAC tx CBOR",
  "artifact.eac.unsigned.description": "Issuance before wallet authorization.",
  "artifact.eac.witness.title": "Witness set CBOR",
  "artifact.eac.witness.description": "Signature from the key required by the policy.",
  "artifact.eac.signed.title": "Signed EAC tx CBOR",
  "artifact.eac.signed.description": "Issuance ready for submission within the transaction validity interval.",
  "artifact.eac.hash.title": "Tx hash",
  "artifact.eac.hash.description": "Identifier used to check the quantity, output, and metadata.",
  "artifact.retire.details.title": "Policy, burn, and metadata",
  "artifact.retire.details.description": "Includes the policy ID, burn, remaining balance, and retirement references.",
  "artifact.retire.unsigned.title": "Unsigned retirement tx CBOR",
  "artifact.retire.unsigned.description": "Retirement before wallet authorization.",
  "artifact.retire.witness.title": "Witness set CBOR",
  "artifact.retire.witness.description": "Signature from the key required by the policy.",
  "artifact.retire.signed.title": "Signed retirement tx CBOR",
  "artifact.retire.signed.description": "Burn ready for submission.",
  "artifact.retire.hash.title": "Retirement tx hash",
  "artifact.retire.hash.description": "Identifier used to check the burn, balance, and metadata.",
  "artifact.mint.details.title": "Policy, asset, and metadata",
  "artifact.mint.details.description": "Includes the policy ID, script, validity interval, metadata under label 721, and transaction summary.",
  "artifact.mint.unsigned.title": "Unsigned mint tx CBOR",
  "artifact.mint.unsigned.description": "Mint before wallet authorization.",
  "artifact.mint.witness.title": "Witness set CBOR",
  "artifact.mint.witness.description": "Signature from the key required by the policy.",
  "artifact.mint.signed.title": "Signed mint tx CBOR",
  "artifact.mint.signed.description": "Mint ready for submission while the policy is valid.",
  "artifact.mint.hash.title": "Tx hash",
  "artifact.mint.hash.description": "Identifier used to check the asset on Preprod.",
} as const satisfies Record<keyof typeof portugueseStaticMessages, string>
